name: 'Compilation Checks'
on:
  push:
    branches-ignore:
    - 'repo'
    paths-ignore:
    - '**.md'
  pull_request:
    branches-ignore:
    - 'repo'
    paths-ignore:
    - '**.md'
concurrency:
  group: '${{ github.workflow }}'
  cancel-in-progress: true
jobs:
  template_check:
    name: 'Check for libs and multisrc compilation'
    runs-on: 'ubuntu-latest'
    steps:
    - id: 'step-0'
      name: 'Clone repo'
      uses: 'actions/checkout@v4'
    - id: 'step-2'
      name: 'Set up JDK'
      uses: 'actions/setup-java@v4'
      with:
        java-version: '21'
        distribution: 'adopt'
    - id: 'step-3'
      name: 'Setup Gradle'
      uses: 'gradle/gradle-build-action@v2'
    - id: 'step-4'
      name: 'Check libs'
      run: './gradlew :compileLibsKotlin'
      if: '${{ steps.step-3.outcome == ''success'' }}'
    - id: 'step-5'
      name: 'Check multisrc'
      run: './gradlew :compileMultiSrcKotlin'
      if: '${{ steps.step-3.outcome == ''success'' }}'
