name: 'Strip release'
on:
  workflow_dispatch: {}
  release: {}
concurrency:
  group: '${{ github.workflow }}'
  cancel-in-progress: true
jobs:
  strip_template:
    name: 'Strips the template'
    runs-on: 'ubuntu-latest'
    if: '742158806 == ${{ github.repository_id }}'
    steps:
    - id: 'step-0'
      name: 'Clone repo'
      uses: 'actions/checkout@v4'
    - id: 'step-2'
      name: 'Set up JDK'
      uses: 'actions/setup-java@v4'
      with:
        java-version: '21'
        distribution: 'adopt'
    - id: 'step-3'
      name: 'Setup Gradle'
      uses: 'gradle/gradle-build-action@v2'
    - id: 'step-4'
      name: 'Strip template'
      run: './gradlew :strip:template'
    - id: 'step-5'
      name: 'Upload strip.zip'
      uses: 'actions/upload-artifact@v4'
      with:
        name: 'stripped-template'
        path: './build/stripped-template.zip'
        if-no-files-found: 'error'
        retention-days: '1'
  edit_release:
    name: 'Add stripped template to release'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'write'
    needs:
    - 'strip_template'
    if: '742158806 == ${{ github.repository_id }}'
    steps:
    - id: 'step-0'
      name: 'Download stripped template'
      uses: 'actions/download-artifact@v4'
      with:
        name: 'stripped-template'
        path: '.'
    - id: 'step-1'
      name: 'Edit release'
      uses: 'irongut/EditRelease@v1.2.0'
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'
        id: '${{ github.event.release.id }}'
        files: './stripped-template.zip'
